### ISSUE TITLE
Compilation Blues

### ISSUE THREAD

**Issue by VeXHarbinger** [ValveSoftware/driver_hydra#5]
I'm sure that the cause of this error is just me, or my env, I don't code in C++ but...  I set my paths as such;
SteamVRRuntimeDir : E:\Games\Steam\steamapps\common\SteamVR
OpenVRDir : E:\Games\Steam\steamapps\common\OpenVR
SixenseSDKDir : E:\Games\Steam\SteamApps\common\Sixense SDK\SixenseSDK
InstallDir : C:\Program Files (x86)\Razer\Hydra (where my Hydra is installed)

Did I misunderstand a path requirement? I receve the following errors;

`Error  C1083   Cannot open include file: 'openvr_driver.h': No such file or directory  driver_hydra    e:\documents\github\driver_hydra\drivers\driver_hydra\driver_hydra.h`

`Error  C1083   Cannot open include file: 'openvr.h': No such file or directory hydra_monitor   e:\documents\github\driver_hydra\tools\hydra_monitor\hydra_monitor.cpp`

I know that one is due to the other project not building but, I'm not sure for the primary failure.  Sorry for such a basic question but, I do more C# Web Dev and this just seems to be out of my wheelhouse.  

I guess another decent question would be, how well does this solution address the expected tracked controller requirements for games.  For example would it work with Unturned?  I just got my new Rift and it seems as though all the games I used to play in VR on my version 1 rift are now no longer VR games.  Maybe I'm still to early an adopter to actually get to enjoy this tech as of yet. 

I'm sorry for the additional questions, I know they really don't go here, I'll google for a Steam Hydra group next.

**Comment by bjj** [comment]
Your OpenVR directory should be pointing at a git clone of our openvr software SDK.

https://github.com/ValveSoftware/openvr
